In [1]:
import pandas as pd

resume_df = pd.read_csv("../data/Resume.csv")
jobs_df = pd.read_csv("../data/monster_com-job_sample.csv")

print("Resume Dataset Shape:", resume_df.shape)
print("Job Dataset Shape:", jobs_df.shape)

Resume Dataset Shape: (2484, 4)
Job Dataset Shape: (22000, 14)

In [2]:
resume_df.head()

,ID,Resume_str,Resume_html,Category
0,16852973,HR ADMINISTRATOR/MARKETING ASSOCIATE\...,"<div class=""fontsize fontface vmargins hmargin...",HR
1,22323967,"HR SPECIALIST, US HR OPERATIONS ...","<div class=""fontsize fontface vmargins hmargin...",HR
2,33176873,HR DIRECTOR Summary Over 2...,"<div class=""fontsize fontface vmargins hmargin...",HR
3,27018550,HR SPECIALIST Summary Dedica...,"<div class=""fontsize fontface vmargins hmargin...",HR
4,17812897,HR MANAGER Skill Highlights ...,"<div class=""fontsize fontface vmargins hmargin...",HR

In [3]:
jobs_df.head()

,country,country_code,date_added,has_expired,job_board,job_description,job_title,job_type,location,organization,page_url,salary,sector,uniq_id
0,United States of America,US,NaN,No,jobs.monster.com,TeamSoft is seeing an IT Support Specialist to...,IT Support Technician Job in Madison,Full Time Employee,"Madison, WI 53702",NaN,http://jobview.monster.com/it-support-technici...,NaN,IT/Software Development,11d599f229a80023d2f40e7c52cd941e
1,United States of America,US,NaN,No,jobs.monster.com,The Wisconsin State Journal is seeking a flexi...,Business Reporter/Editor Job in Madison,Full Time,"Madison, WI 53708",Printing and Publishing,http://jobview.monster.com/business-reporter-e...,NaN,NaN,e4cbb126dabf22159aff90223243ff2a
2,United States of America,US,NaN,No,jobs.monster.com,Report this job About the Job DePuy Synthes Co...,Johnson & Johnson Family of Companies Job Appl...,"Full Time, Employee",DePuy Synthes Companies is a member of Johnson...,Personal and Household Services,http://jobview.monster.com/senior-training-lea...,NaN,NaN,839106b353877fa3d896ffb9c1fe01c0
3,United States of America,US,NaN,No,jobs.monster.com,Why Join Altec? If you’re considering a career...,Engineer - Quality Job in Dixon,Full Time,"Dixon, CA",Altec Industries,http://jobview.monster.com/engineer-quality-jo...,NaN,Experienced (Non-Manager),58435fcab804439efdcaa7ecca0fd783
4,United States of America,US,NaN,No,jobs.monster.com,Position ID# 76162 # Positions 1 State CT C...,Shift Supervisor - Part-Time Job in Camphill,Full Time Employee,"Camphill, PA",Retail,http://jobview.monster.com/shift-supervisor-pa...,NaN,Project/Program Management,64d0272dc8496abfd9523a8df63c184c

In [4]:
print("Resume Dataset Columns:")
print(resume_df.columns)

print("\nJob Dataset Columns:")
print(jobs_df.columns)

Resume Dataset Columns:
Index(['ID', 'Resume_str', 'Resume_html', 'Category'], dtype='object')

Job Dataset Columns:
Index(['country', 'country_code', 'date_added', 'has_expired', 'job_board',
       'job_description', 'job_title', 'job_type', 'location', 'organization',
       'page_url', 'salary', 'sector', 'uniq_id'],
      dtype='object')

In [5]:
print(resume_df.isnull().sum())

print()

print(jobs_df.isnull().sum())

ID             0
Resume_str     0
Resume_html    0
Category       0
dtype: int64

country                0
country_code           0
date_added         21878
has_expired            0
job_board              0
job_description        0
job_title              0
job_type            1628
location               0
organization        6867
page_url               0
salary             18554
sector              5194
uniq_id                0
dtype: int64

In [6]:
resume_df.info()

print("\n-----------------\n")

jobs_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2484 entries, 0 to 2483
Data columns (total 4 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   ID           2484 non-null   int64
 1   Resume_str   2484 non-null   object
 2   Resume_html  2484 non-null   object
 3   Category     2484 non-null   object
dtypes: int64(1), object(3)
memory usage: 77.8+ KB

-----------------

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 22000 entries, 0 to 21999
Data columns (total 14 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   country          22000 non-null  object
 1   country_code     22000 non-null  object
 2   date_added       122 non-null    object
 3   has_expired      22000 non-null  object
 4   job_board        22000 non-null  object
 5   job_description  22000 non-null  object
 6   job_title        22000 non-null  object
 7   job_type         20372 non-null  object
 8   location         22000 non-null  object
 9   organization     15133 non-null  object
 10  page_url         22000 non-null  object
 11  salary           3446 non-null   object
 12  sector           16806 non-null  object
 13  uniq_id          22000 non-null  object
dtypes: object(14)
memory usage: 2.3+ MB

In [7]:
import re
import string
import nltk

from nltk.corpus import stopwords
from nltk.stem import WordNetLemmatizer

nltk.download("stopwords")
nltk.download("wordnet")
nltk.download("omw-1.4")

stop_words = set(stopwords.words("english"))
lemmatizer = WordNetLemmatizer()

[nltk_data] Downloading package stopwords to
[nltk_data]     /Users/saksham/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!
[nltk_data] Downloading package wordnet to /Users/saksham/nltk_data...
[nltk_data]   Package wordnet is already up-to-date!
[nltk_data] Downloading package omw-1.4 to /Users/saksham/nltk_data...
[nltk_data]   Package omw-1.4 is already up-to-date!

In [8]:
def preprocess_text(text):
    if not isinstance(text, str):
        return ""

    # lowercase
    text = text.lower()

    # remove urls
    text = re.sub(r"http\S+|www\S+", "", text)

    # remove emails
    text = re.sub(r"\S+@\S+", "", text)

    # remove numbers
    text = re.sub(r"\d+", "", text)

    # remove punctuation
    text = text.translate(str.maketrans("", "", string.punctuation))

    # remove extra spaces
    text = re.sub(r"\s+", " ", text).strip()

    # tokenize
    words = text.split()

    # remove stopwords & lemmatize
    words = [
        lemmatizer.lemmatize(word)
        for word in words
        if word not in stop_words
    ]

    return " ".join(words)

In [9]:
resume_df["Clean_Resume"] = resume_df["Resume_str"].apply(preprocess_text)

jobs_df["Clean_Job"] = jobs_df["job_description"].apply(preprocess_text)

In [10]:
print("Original Resume:\n")
print(resume_df["Resume_str"][0][:500])

print("\n\nCleaned Resume:\n")
print(resume_df["Clean_Resume"][0][:500])

Original Resume:

         HR ADMINISTRATOR/MARKETING ASSOCIATE

HR ADMINISTRATOR       Summary     Dedicated Customer Service Manager with 15+ years of experience in Hospitality and Customer Service Management.   Respected builder and leader of customer-focused teams; strives to instill a shared, enthusiastic commitment to customer service.         Highlights         Focused on customer satisfaction  Team management  Marketing savvy  Conflict resolution techniques     Training and development  Skilled multi-task


Cleaned Resume:

hr administratormarketing associate hr administrator summary dedicated customer service manager year experience hospitality customer service management respected builder leader customerfocused team strives instill shared enthusiastic commitment customer service highlight focused customer satisfaction team management marketing savvy conflict resolution technique training development skilled multitasker client relation specialist accomplishment missouri dot supervisor training certification certif

In [11]:
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics.pairwise import cosine_similarity

In [12]:
job_description = jobs_df["Clean_Job"].iloc[0]

print(job_description[:1000])

teamsoft seeing support specialist join client madison wi ideal candidate must least year experience field need familiar variety field concept practice procedure position relies extensive experience judgment plan accomplish goal required skills• call tracking software• phone based technical support• problem documentation communication• remote desktop management tools• respond customer requests• general understanding landesk• microsoft office suitefind teamsoft madison area technology leader consultant owned operated managed consultant teamsoft clear choice career join teamsoft family todaydid know• teamsoft offer salaried option many position include week pto great benefits• teamsoft business since • teamsofts owner local professional possess wealth experience application development business analysis project management• teamsofts recruiter knowledgeable friendly ready help make next great career move• teamsoft offer full benefit suite w consultant including k plan vested dollar dollar

In [13]:
documents = resume_df["Clean_Resume"].tolist()

documents.append(job_description)

vectorizer = TfidfVectorizer(max_features=5000)

tfidf_matrix = vectorizer.fit_transform(documents)

In [14]:
similarity_scores = cosine_similarity(
    tfidf_matrix[-1],
    tfidf_matrix[:-1]
)

resume_df["Similarity"] = similarity_scores.flatten()

In [15]:
top_candidates = resume_df.sort_values(
    by="Similarity",
    ascending=False
)

top_candidates[
    ["Category", "Similarity"]
].head(10)

                  Category  Similarity
87                      HR    0.189484
2130      PUBLIC-RELATIONS    0.165685
2324                  ARTS    0.156103
2071      PUBLIC-RELATIONS    0.153446
91                      HR    0.152909
1155            CONSULTANT    0.148797
666   BUSINESS-DEVELOPMENT    0.146956
646   BUSINESS-DEVELOPMENT    0.146402
1216            CONSULTANT    0.143931
1205            CONSULTANT    0.143777

In [16]:
skills = [
    "python","java","c++","c","sql","mysql","postgresql",
    "html","css","javascript","react","node.js","express",
    "mongodb","flask","django","git","github","docker",
    "kubernetes","aws","azure","gcp","linux","excel",
    "power bi","tableau","numpy","pandas","matplotlib",
    "scikit-learn","tensorflow","keras","pytorch",
    "machine learning","deep learning","nlp",
    "data analysis","data science","communication",
    "leadership","problem solving","teamwork","project management"
]

In [17]:
def extract_skills(text):
    text = text.lower()

    found = []

    for skill in skills:
        if skill in text:
            found.append(skill)

    return sorted(list(set(found)))

In [18]:
job_skills = extract_skills(jobs_df["job_description"].iloc[0])

print(job_skills)

['c', 'communication', 'project management']

In [19]:
resume_df[["Category","Skills"]].head()

KeyError: "['Skills'] not in index"

In [20]:
resume_df["Skills"] = resume_df["Resume_str"].apply(extract_skills)

In [21]:
print(resume_df.columns)

Index(['ID', 'Resume_str', 'Resume_html', 'Category', 'Clean_Resume',
       'Similarity', 'Skills'],
      dtype='object')

In [22]:
resume_df[["Category", "Skills"]].head()

  Category                                             Skills
0       HR                [aws, c, data analysis, leadership]
1       HR        [c, communication, git, project management]
2       HR  [c, excel, express, leadership, project manage...
3       HR                          [c, communication, excel]
4       HR  [aws, c, excel, leadership, problem solving, p...

In [23]:
best_candidate = top_candidates.iloc[0]

candidate_skills = set(best_candidate["Skills"])

required_skills = set(job_skills)

matched = candidate_skills & required_skills

missing = required_skills - candidate_skills

print("Candidate Category:", best_candidate["Category"])
print("\nMatched Skills:")
print(sorted(matched))

print("\nMissing Skills:")
print(sorted(missing))

KeyError: 'Skills'

In [24]:
top_candidates = resume_df.sort_values(
    by="Similarity",
    ascending=False
)

In [25]:
best_candidate = top_candidates.iloc[0]

candidate_skills = set(best_candidate["Skills"])

required_skills = set(job_skills)

matched = candidate_skills & required_skills
missing = required_skills - candidate_skills

print("Candidate Category:", best_candidate["Category"])
print("\nMatched Skills:")
print(sorted(matched))

print("\nMissing Skills:")
print(sorted(missing))

Candidate Category: HR

Matched Skills:
['c', 'communication']

Missing Skills:
['project management']